#! /usr/bin/env bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

START_DIR=$HOME'/Git/JsObjects/JavaScript/React/'

function check-return-value {
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo -e ${LIGHT_RED}"Error"${NC}
    else
        echo -e ${LIGHT_GREEN}"Ok"${NC}
    fi
}

function check-dir {
    cd $START_DIR
    cd $1
    pwd
    npm audit --json > elf-audit.json
    check-return-value
}

function get-directories-containing-package-json {
    FindNp package.json | xargs -I{} dirname {} | xargs printf "check-dir %s\n" | sort
}

#check-dir BootstrapStarter
#check-dir Cordova
#check-dir Crafty01
#check-dir Firebase
#check-dir MilesFunction
#check-dir MongoStuff
#check-dir MongoTalk
check-dir Simple01
#check-dir Simple02
#check-dir Simple03
#check-dir TestMe01
#check-dir ToolTip
#check-dir Week05BootStrap
#check-dir Week07Midterm
#check-dir Week08-GitPractice
#check-dir Week08-GitPractice02
#check-dir Week09Android
#check-dir Yo01
